# Site settings
title: Open Data Minnesota
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  An open listing of all open and freely usable APIs for data about and relating
  to Minnesota. Pull Requests are highly encouraged!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://opendatamn.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown

collections:
- live_data
